---@type vim.lsp.Config
return {
	settings = {
		["rust-analyzer"] = {
			cargo = {
				allFeatures = true,
				-- Without this, anything generated by a build script or a proc macro
				-- (serde derives, for instance) reads as an unresolved symbol.
				buildScripts = { enable = true },
			},
			procMacro = { enable = true },
			checkOnSave = true,
			check = {
				command = "clippy",
			},
			inlayHints = {
				parameterHints = { enable = true },
				typeHints = { enable = true },
				closingBraceHints = { enable = false },
			},
		},
	},
}
